<div class="slider-revolution-update-list">


    <h3 class="version-number">Version 5.3.1.6.1 StarPath (13th February 2017)</h3>
    <div class="bugfix"><strong style="font-weight:700">BUGFIXES</strong></div>
    <ul>
        <li>Fixed not defined jQuery javascript error on slider notices.</li>
    </ul>


    <h3 class="version-number">Version 5.3.1.6 StarPath (10th February 2017)</h3>
    <div class="newfeature"><strong style="font-weight:700">NEW FEATURES</strong></div>
    <ul>
        <li>Introducing placeholders to gallery sliders (already available for post/stream sources)</li>
        <li>Added Ease and Speed to Scroll Below Action to make individual Scroll Effects</li>
        <li>Added option to delete User Slide Templates</li>
        <li>Added option to show layers on all Slides in Carousel mode</li>
        <li>Added option to use YouTube video cover for YouTube video background on slides</li>
        <li>New Option added to fade Out Hero Content optional when Parallax Scroll activated, like Slider BG, Layer, Static Layer, Parallax Layer</li>
        <li>Added an option to set the Group Sizes by %. Content of Groups can be set also % based</li>
        <li>Added new Option for Easing and Speed of Carousel Slides</li>
        <li>Added an option which allows to show Carousel first in Viewport.</li>
        <li>Added option for layers to add an tabindex.</li>
        <li>New Brasilian/Portuguese translation added! Special thanks to Diego Fernandes</li>
        <li>Introducing Rows and Columns as Layer Groups</li>
        <li>Added Layer Groups for logical and physical grouping of Layers.</li>
        <li>Animations are now allowed in multiple levels for Groups, Rows, Columns and wrapped Layers</li>
        <li>Added Margin for relative Layers (Columns, Rows, Layers in Columns)</li>
        <li>Rows can be sorted within Top, Middle and Bottom Containers</li>
        <li>Added Post ID {{id}} into the Meta List</li>
        <li>Added Layer Background Images for Text, Column, Row, Group and Shape</li>
        <li>Added Instagram Image Filtering for Slide Backgrounds</li>
        <li>Slides will receive an Auto Height with Rows and Columns</li>
        <li>Introducing Right Click Content Menu on Layers and BG in Slide Editor for quick Edit mode and shortcuts</li>
        <li>Introducing the Object Library with dozens of new Images, BG Images and Objects</li>
        <li>Added Font Icons to Object Library for quicker icon selection within a Text Layer</li>
        <li>Copy/Paste Layer styles easily from one Layer to the other</li>
        <li>Selecting more than one Layer, to move them together, now available</li>
        <li>Introducing logical grouping of Layers</li>
        <li>Added CSS Blend Modes for Text Layer to get some exclusive effects on backgrounds. (Will not work with older IE Browser)</li>
        <li>Easy Editing and Movement of Groups and Layers in Groups</li>
        <li>Added CTRL / CMD + Click function to enable multiple selections</li>
        <li>Added device based level for Spacings like Paddings, Margins, Text-Aligns which can be set now individual based on Responsive Level</li>
        <li>Added Ken Burns Live Editor</li>
        <li>Added option to include all Slider Revolution JavaScript libraries on page load</li>
        <li>Added new option on Slider Import, to be able to create blank pages with the Slider inside</li>
    </ul>
    <div class="change"><strong style="font-weight:700">CHANGES</strong></div>
    <ul>
        <li>Layout of Sticky Layers Settings has been changed</li>
        <li>Removed unneeded CSS Lines and minified the CSS Export of settings.css</li>
        <li>Merged Google Font loading into less calls</li>
        <li>Removed unneeded CSS Lines and minified the CSS Export of settings.css</li>
        <li>Added Version Checking for Loaded Modules and some function to handle Cache issues</li>
        <li>Redesigned the Import Process of Slider and Slide Templates</li>
        <li>Carousel Slides will always fade in first without a Start Slide effect which was annoying in some kind of situations</li>
        <li>Carousel Slider will act on Swipe even due Clickable elements</li>
        <li>Extended Idle/Hover Style Editor in Slide Editor mode for quicker work processes</li>
        <li>jQuery and Slider CSS Editor also available due Slide Editor mode to simplfy the Slide building processes</li>
        <li>Static/Global Styles are now obsolete</li>
        <li>Font Awesome Library Updated to 4.7.0</li>
        <li>Improved loading speed at Slider Overview</li>
        <li>Changed Timeline Interface for better and easier Time Settings</li>
        <li>Add-On Deactivation Button more visual</li>
        <li>Changed Button Hover feature to allow Hover during the Layer Animation already. Direct feedback from Button to customer</li>
        <li>Changed the Layer Animation Core. Introducing Timeline feature which will allow build multiple frames within one Layer Animation</li>
        <li>Improved the Timeline functionality</li>
        <li>Fixed Template and Object Library Loading methods to improve the Loading speed of Background Edit Modes</li>
        <li>Removed deprecated function, removed with PHP 7</li>
        <li>Padding, Margin and Text Align are now saved for all devices on saving a style</li>
    </ul>
    <div class="bugfix"><strong style="font-weight:700">BUGFIXES</strong></div>
    <ul>
        <li>Slide Link was not linking to the correct Slides in some cases.</li>
        <li>Slide Link was not visible at start</li>
        <li>Fixed Bug in "Add New" Page/Post, Slider Selector overview in Visual Composer not working properly</li>
        <li>Fixed an issue where static element Position Calculation was broken in some kind of cases</li>
        <li>Fixed an issue where inline styled Content lost its FontWeight, Line Height and Font Size in some kind of cases</li>
        <li>Fixed a Rendering issue with Row Oversizing in case Image element added into Columns</li>
        <li>Fixed "Child Elements Responsive" to stay at "off" after Slide Editor reload</li>
        <li>ID of Wrapper Elements added via Option was not available on Frontend</li>
        <li>Fixed date selector for Visible From/To z-index issue</li>
        <li>Fixed Layer Action issues where multiple Actions on same Layer was not recognised on FrontEnd</li>
        <li>Fixed Border issues on Buttons</li>
        <li>Loading of Video Elements in Rows driven by Actions was not Showing up in some kind of rare cases</li>
        <li>Hidden "Max Width" field is available in Auto Mode again</li>
        <li>Fixed notice in output.class.php for certain Sliders</li>
        <li>Fixed a strange Effect on Scroll where Stick Style Menu was not clearly docked on the top, but was flickering before docking</li>
        <li>Fixed Image Filter issues related to Slide Changes</li>
        <li>Fixed Slide Transitions where Transion should happen based on the Slide Direction</li>
        <li>Flickering issue by Static Layers with Action fixed</li>
        <li>Fixed an issue where Quick and Long LAyer Actions made Layers unavailable</li>
        <li>Fixed Order issues on Row Duplication</li>
        <li>RTL Backend Issues with the new Objet Library has been fixed</li>
        <li>Fixed missing Styles after Hovering Layers in Firefox</li>
        <li>Toggled Content without Action was not swapping its Toggled Status. Issue is fixed now</li>
        <li>Fixed Grid Based Static Layer Positions in Carousel Sliders</li>
        <li>Fixed Issue where adding New Layer due Context menu was broken</li>
        <li>Fixed Backend Margin calculation issue on Backend. Frontend and Backend was behaving differently. Now Frontend view covers backend view</li>
        <li>Fixed Split Animation not beeing written in some cases for the out animation</li>
        <li>Fixed Export to HTML issue with background images creating HTML an error</li>
        <li>Fixed Global CSS not opening</li>
        <li>Fixed rare Slider Import bug</li>
        <li>Fixed border-width not saving correctly in Style Templates</li>
        <li>Fixed warning in not existing pages caused by Slider Revolution</li>
        <li>Fixed the Row / Column  / InnerLayer Timing in Backend and in Frontend</li>
        <li>Split Animation did not change the Timeline Behaviours directly. This has been fixed now</li>
        <li>Hover on SVG Elements was not coloring well the Idle or Hover status has been fixed</li>
        <li>Fixed installation warning that could occur in certain installations</li>
        <li>Fixed layer video cover not showing in Slide Editor for imported Slider</li>
        <li>Fixed Slider Pack import sometimes having wrong orders in created Draft Page</li>
        <li>Layers other than text no longer have "Open Sans" as font-family as default</li>
        <li>Replace Image URL's now properly working with Static Layers</li>
        <li>Fixed a problem where Sliders with Full Slide link in Carousel and in some special mode had issues with the Full Slide Link layer</li>
        <li>Static Layer issues with Invisible Slides where Static Layers were not disappearing on Unvisible Slides on demenad</li>
        <li>Fixed WhiteBoard's multiple "Hand" issue</li>
        <li>Fixed Hover / Idle issues where quick focus/blur events would not remove the Hover animation effects from the layers</li>
        <li>Fixed Syntax and Logical Issues like Removing a Slide from Slider based on the Feedback of Sébastien Ledan (http://dotevo.com)! Thank you for the great Feedbacks and Suggestions</li>
        <li>Fixed Slider disappearing in IE11 if Parallax Mode is activated. Double parameter definition in Animation Engine has been fixed</li>
        <li>Fixed an issue where all extension modules should be loaded at once. Folder Name in Path has been renamed from extension to extensions</li>
        <li>Fixed PHP7 issue: "Fatal error: Uncaught Error: [] operator not supported for strings"</li>
        <li>Fixed preview issue where the Slide Editor was not working properly after opening and closing the preview</li>
        <li>Fixed preview in Slide Editor, to show the current changes made without saving the Slide</li>
        <li>Fixed an issue where cross referencing Static Layers were disappeared</li>
        <li>Disappearing elements on Drag & Drop in Slide Editor has been fixed</li>
        <li>Fixed an issue where in Viewpoint Scrolled Slides did not start straight but with a small delay</li>
        <li>Fixed Restarted Static Layers which are animating on each Slide if Start time was smaller than 100ms</li>
        <li>Fixed Warning: Illegal string offset 'width' in [...] object-library.class.php on line 994</li>
        <li>Fixed Global Settings getting reset in certain cases. Which ultimately causes for some customers blank Sliders as the JavaScript files are no longer loaded in the footer</li>
        <li>Fixed bug where actions in Static Layers could be lost after saving</li>
        <li>Improved Google Font loading by removing duplicated inclusions</li>
        <li>Fixed Slot Animation Issues where Slot Amount was ignored in Fade Slots Transitions</li>
        <li>Fixed issue where Layer On Complete Event was triggered twice on Slide Changes. This had negative influence i.e. on Add Ons like White Board</li>
        <li>Fixed SVG Resizing issues in the Slide Editor after changing SVG Source of an Object Layer</li>
        <li>Fixed Dotted Overlays issues on Slides</li>
        <li>Fixed CTRL+S (CMD+S) Quick save functions</li>
        <li>Fixed Image Size and Aspect Ratio issues in Slide Editor</li>
        <li>Fixed a bug where FullScreen Slider Offset Container parameter was not working with the Carousel Slider Layout</li>
        <li>Fixed Slide Direction Animation on Horizontal and Vertical direction when slide change has been triggered by Mouse Scroll</li>
        <li>Fixed Ken Burns Issues where Horizontal and Vertical Start Offsets were not implemented well</li>
        <li>YouTube Playback on Mobile Phones lost Focus and lost Video after Slide Change in some rare situations has been fixed</li>
        <li>Fixed a YouTube Bug which was not allow to trigger YouTube Videos via Layer Action on Mobiles</li>
        <li>Fixed Blurry Buttons in YouTube Videos on Mobile Phones</li>
        <li>Issue where Pendulum Easing was ignored in frontend fixed</li>
        <li>Parallax effect on Background Media was not working without Existing Layer in Slide has been fixed</li>
        <li>Facebook Timeline Images did not show under certain circumstances before. Now they do.
    </ul>

    <h3 class="version-number">Version 5.2.6.3 StarPath (28th October 2016)</h3>
    <div class="newfeature"><strong style="font-weight:700">NEW FEATURES</strong></div>
    <ul>
        <li>Add to cart action added to layer actions for product based sliders</li>
    </ul>
    <div class="bugfix"><strong style="font-weight:700">CHANGES</strong></div>
    <ul>
        <li>Disabled autoload when checking for class existance</li>
        <li>Removed unused WMPL related code</li>
    </ul>
    <div class="bugfix"><strong style="font-weight:700">BUGFIXES</strong></div>
    <ul>
        <li>Fixed error on saving custom slider preset</li>
    </ul>



    <h3 class="version-number">Version 5.2.6.2 StarPath (15th October 2016)</h3>
    <div class="bugfix"><strong style="font-weight:700">BUGFIXES</strong></div>
    <ul>
        <li>Forced https protocol on sliders thumbnails urls</li>
        <li>Fixed ajax error bug when saving slide after duplicating layer</li>
        <li>Removed deprecated characters from name attribute in backend layout</li>
        <li>Fix for missing title attribute in ACL resource</li>
        <li>Fix for undefined function error warning when importing template online</li>
    </ul>



    <h3 class="version-number">Version 5.2.6.1 StarPath (1st September 2016)</h3>
    <div class="newfeature"><strong style="font-weight:700">NEW FEATURES</strong></div>
    <ul>
        <li>Positioned manual animation timing dialog to layer it was called for</li>
    </ul>
    <div class="change"><strong style="font-weight:700">CHANGES</strong></div>
    <ul>
        <li>Setting default font family if not specified on captions saving</li>
        <li>Updated translation functions calls</li>
        <li>Minified addons scripts</li>
        <li>Removed depricated use of old Magento helpers</li>
    </ul>
    <div class="bugfix"><strong style="font-weight:700">BUGFIXES</strong></div>
    <ul>
        <li>Fixed bug with importing template sliders for databases with custom table prefix</li>
        <li>Fixed bug with edit layers timeline split text time incorrectly added to each layer</li>
        <li>Fix for add slider enter title dialog displaying under templates shop dialog</li>
        <li>Fix for showing all hidden dialogs after image inserting</li>
        <li>Fix for delete confirmation popover displaying under select image slide out dialog</li>
        <li>Fix for guide lines zindex issue with save styles dropdown</li>
        <li>Fix for color picker edit field zindex</li>
        <li>Fix for preview captions after inserting new caption style</li>
        <li>Fix for navigation save function</li>
        <li>Fix for saving css captions</li>
        <li>Fix for dialog zIndex problems</li>
        <li>Fix for javascript error on slide editor</li>
        <li>Fix for color picker edit field</li>
        <li>Fix for not showing inline css template and layer dialogs</li>
        <li>Fix for media gallery dialog z-index issue</li>
        <li>Fixed typo in video settings autoplay option</li>
        <li>Fix for audio mp3 layer in slide editor. Fix for whiteboard addon</li>
        <li>Fixed error with backup addons</li>
        <li>Fix for left arrow override</li>
        <li>Fix for svg import from template</li>
        <li>Fix for product based slider slide links</li>
        <li>Fix for product based view link, prices and preview</li>
    </ul>



    <h3 class="version-number">Version 5.2.6 StarPath (28th July 2016)</h3>
    <div class="newfeature"><strong style="font-weight:700">NEW FEATURES</strong></div>
    <ul>
        <li>Slider Revolution Magento 2 Extension Version Created!</li>
    </ul>

</div>