<?php

use \Nwdthemes\Revslider\Model\Revslider\Framework\RevSliderBase;
use \Nwdthemes\Revslider\Model\Revslider\RevSliderOperations;

$operations = new RevSliderOperations($framework, $query, $curl, $filesystemHelper, $images, $resource, $googleFonts);
$arrValues = $operations->getGeneralSettingsValues();

$includes_globally = RevSliderBase::getVar($arrValues, 'includes_globally', 'on');
$pages_for_includes = RevSliderBase::getVar($arrValues, 'pages_for_includes', '');

$show_dev_export = RevSliderBase::getVar($arrValues, 'show_dev_export', 'off');

$change_font_loading = RevSliderBase::getVar($arrValues, 'change_font_loading', '');

$pack_page_creation = RevSliderBase::getVar($arrValues, 'pack_page_creation', 'on');
$single_page_creation = RevSliderBase::getVar($arrValues, 'single_page_creation', 'off');

$width = RevSliderBase::getVar($arrValues, 'width', 1240);
$width_notebook = RevSliderBase::getVar($arrValues, 'width_notebook', 1024);
$width_tablet = RevSliderBase::getVar($arrValues, 'width_tablet', 778);
$width_mobile = RevSliderBase::getVar($arrValues, 'width_mobile', 480);

?>
<div id="dialog_general_settings" title="<?php echo __("General Settings"); ?>" style="display:none;">

	<div class="settings_wrapper unite_settings_wide">
		<form name="form_general_settings" id="form_general_settings">
			<script type="text/javascript">
				g_settingsObj['form_general_settings'] = {};
			</script>
			<table class="form-table">
				<tbody>
					<tr id="includes_globally_row" valign="top">
						<th scope="row">
							<?php echo __("Include RevSliderSlider libraries globally:"); ?>
						</th>
						<td>
							<span id="includes_globally_wrapper" class="radio_settings_wrapper">
							<div class="radio_inner_wrapper">
								<input type="radio" id="includes_globally_1" value="on" name="includes_globally" <?php $framework->checked($includes_globally, 'on'); ?>>
								<label for="includes_globally_1" style="cursor:pointer;"><?php echo __("On"); ?></label>
							</div>
				
							<div class="radio_inner_wrapper">
								<input type="radio" id="includes_globally_2" value="off" name="includes_globally" <?php $framework->checked($includes_globally, 'off'); ?>>
								<label for="includes_globally_2" style="cursor:pointer;"><?php echo __("Off"); ?></label>
							</div>
							</span>
				
							<div class="description_container">
								<span class="description"><?php echo __("ON - Add CSS and JS Files to all pages. </br>Off - CSS and JS Files will be only loaded on specified pages."); ?></span>
							</div>
						</td>
					</tr>								
					<tr id="pages_for_includes_row" valign="top">
						<th scope="row">
							<?php echo __("Pages to include RevSliderSlider libraries:"); ?>
						</th>
						<td>
                            <input type="text" class="regular-text" id="pages_for_includes" name="pages_for_includes" value="<?php echo $pages_for_includes; ?>">
							<div class="description_container">
								<span class="description"><?php echo __("Specify the page handles that the front end includes will be included in. Example: cms_page_view,catalog_product_view"); ?></span>
			
							</div>
						</td>
					</tr>
					<tr id="show_dev_export_row" valign="top">
						<th scope="row">
							<?php echo __("Enable Markup Export option:"); ?>
						</th>
						<td>
							<span id="show_dev_export_wrapper" class="radio_settings_wrapper">
								<div class="radio_inner_wrapper">
									<input type="radio" id="show_dev_export_1" value="on" name="show_dev_export" <?php $framework->checked($show_dev_export, 'on'); ?>>
									<label for="show_dev_export_1" style="cursor:pointer;"><?php echo __("On"); ?></label>
								</div>
				
								<div class="radio_inner_wrapper">
									<input type="radio" id="show_dev_export_2" value="off" name="show_dev_export" <?php $framework->checked($show_dev_export, 'off'); ?>>
									<label for="show_dev_export_2" style="cursor:pointer;"><?php echo __("Off"); ?></label>
								</div>					
							</span>					
							<div class="description_container">
                                <span class="description"><?php echo __("This will enable the option to export the Slider Markups to copy/paste it directly into websites."); ?></span>
							</div>
						</td>
					</tr>							
					<tr id="show_dev_export_row" valign="top">
						<th scope="row">
							<?php echo __("Font Loading URL:"); ?>
						</th>
						<td>
							<input id="change_font_loading" name="change_font_loading" type="text" class="regular-text" value="<?php echo $change_font_loading; ?>">
							<div class="description_container">
								<span class="description"><?php echo __("Insert something in it and it will be used instead of http://fonts.googleapis.com/css?family= (For example: http://fonts.useso.com/css?family= which will also work for chinese visitors)"); ?></span>				
							</div>
						</td>
					</tr>

					<tr id="advanced_resonsive_sizes_row" valign="top">
						<th scope="row">
							<?php echo __("Default Settings for Advanced Responsive Grid Sizes:"); ?>
						</th>
						<td>
							<div><?php echo __('Desktop Grid Width'); ?>
							<input id="width" name="width" type="text" class="textbox-small" value="<?php echo $width; ?>"></div>
							<div><?php echo __('Notebook Grid Width'); ?>
							<input id="width_notebook" name="width_notebook" type="text" class="textbox-small" value="<?php echo $width_notebook; ?>"></div>
							<div><?php echo __('Tablet Grid Width'); ?>
							<input name="width_tablet" type="text" class="textbox-small" value="<?php echo $width_tablet; ?>"></div>
							<div><?php echo __('Mobile Grid Width'); ?>
							<input name="width_mobile" type="text" class="textbox-small" value="<?php echo $width_mobile; ?>"></div>
							
							<div class="description_container">
                                <span class="description"><?php echo __("Define the default Grid Sizes for devices: Desktop, Tablet and Mobile"); ?></span>
							</div>
						</td>
					</tr>
					<tr valign="top">
						<th scope="row">
							<?php echo __("Enable Blank Page Creation for Slider Packages:"); ?>
						</th>
						<td>
                            <span id="pack_page_creation_box_wrapper" class="radio_settings_wrapper">
                                <div class="radio_inner_wrapper">
                                    <input type="radio" id="" value="on" name="pack_page_creation" <?php $framework->checked($pack_page_creation, 'on'); ?>>
                                    <label for="" style="cursor:pointer;"><?php echo __("On"); ?></label>
                                </div>

                                <div class="radio_inner_wrapper">
                                    <input type="radio" id="" value="off" name="pack_page_creation" <?php $framework->checked($pack_page_creation, 'off'); ?>>
                                    <label for="" style="cursor:pointer;"><?php echo __("Off"); ?></label>
                                </div>
                            </span>
							<div class="description_container">
								<span class="description"><?php echo __("Enable option to automatically create a Blank Page if a Slider Pack is installed."); ?></span>
							</div>
						</td>
					</tr>
					<tr valign="top">
						<th scope="row">
							<?php echo __("Enable Blank Page Creation for Single Sliders:"); ?>
						</th>
						<td>
                            <span id="single_page_creation_box_wrapper" class="radio_settings_wrapper">
                                <div class="radio_inner_wrapper">
                                    <input type="radio" id="" value="on" name="single_page_creation" <?php $framework->checked($single_page_creation, 'on'); ?>>
                                    <label for="" style="cursor:pointer;"><?php echo __("On"); ?></label>
                                </div>

                                <div class="radio_inner_wrapper">
                                    <input type="radio" id="" value="off" name="single_page_creation" <?php $framework->checked($single_page_creation, 'off'); ?>>
                                    <label for="" style="cursor:pointer;"><?php echo __("Off"); ?></label>
                                </div>
                            </span>
							<div class="description_container">
								<span class="description"><?php echo __("Enable option to automatically create a Blank Page if a Single Slider is installed."); ?></span>
							</div>
						</td>
					</tr>
                </tbody>
            </table>
		</form>
	</div>
<br>

<a id="button_save_general_settings" class="button-primary" original-title=""><?php echo __("Update"); ?></a>
<span id="loader_general_settings" class="loader_round mleft_10" style="display: none;"></span>

</div>
